name: Front

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: rm -rf ./front && git clone https://github.com/AnarionBe/Orgath.git ./front && cd ./front && npm ci && npm run build --if-present && cd ../ && mv ./front/build ./public && rm -rf ./front
